name: Deploy Node Backend to EC2

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to EC2 server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}    # Updated secret name
          port: 22
          source: "node_backend/*"
          target: "/home/ubuntu/site_safety_monitor"

      - name: SSH into EC2 and restart backend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}    # Updated secret name
          port: 22
          script: |
            cd /home/ubuntu/site_safety_monitor
            npm install
            # Check if pm2 is installed globally, install if missing
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi
            # Restart the app, or start it if not running
            pm2 restart safety-backend || pm2 start server.js --name "safety-backend"
        shell: bash
